# Generated by Django 4.0.6 on 2023-04-03 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contectMe', '0002_alter_contectme_emailc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contectme',
            name='datetime',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
