# Generated by Django 4.0.6 on 2023-04-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contectMe', '0003_contectme_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contectme',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
