# Generated by Django 4.0.6 on 2023-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('explain_me', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
