# Generated by Django 4.0.6 on 2023-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
