# Generated by Django 4.0.6 on 2023-01-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i_do',
            options={'verbose_name_plural': 'Name job'},
        ),
    ]
