# Generated by Django 4.0.6 on 2023-01-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_i_do_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i_do',
            options={},
        ),
        migrations.AlterField(
            model_name='i_do',
            name='job_name',
            field=models.CharField(max_length=200),
        ),
    ]
