# Generated by Django 4.0.6 on 2023-01-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
