# Generated by Django 4.0.6 on 2023-02-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(max_length=200, null=True)),
                ('explain_blog', models.CharField(max_length=200)),
                ('blog_pic', models.ImageField(upload_to='media/picture')),
                ('name_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.i_do')),
            ],
        ),
    ]
