# Generated by Django 4.0.6 on 2023-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='explain',
            field=models.TextField(),
        ),
    ]
