# Generated by Django 4.0.6 on 2023-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_blog',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='explain_blog',
            field=models.TextField(),
        ),
    ]
