# Generated by Django 4.0.6 on 2023-02-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='name_job',
            new_name='i_do',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='name_job',
            new_name='i_do',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='job_name',
            new_name='i_do',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='job_name',
            new_name='i_do',
        ),
    ]
