# Generated by Django 4.0.6 on 2023-04-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_contectme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContectMe',
        ),
    ]
