# Generated by Django 4.0.6 on 2023-04-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_delete_contectme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
