# Generated by Django 4.0.6 on 2023-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_educate_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
