# Generated by Django 4.0.6 on 2023-06-07 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0018_alter_portfolio_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='like',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='like',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
