# Generated by Django 4.0.6 on 2023-06-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_alter_blog_options_blog_title1_blog_title1_explain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='like',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
