# Generated by Django 4.0.6 on 2023-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_remove_portfolio_like_portfolio_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
