# Generated by Django 4.1.3 on 2024-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_alter_portfolio_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
